import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilRootWrapper from "./recoilWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Styling Cloud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RecoilRootWrapper>
      <html>
        <body className="overscroll-y-none">
          <div className="flex w-screen items-center justify-center bg-white">
            <div className="relative h-full w-full max-w-[480px] select-none">
              {children}
            </div>
          </div>
        </body>
      </html>
    </RecoilRootWrapper>
  );
}
